<a href="https://colab.research.google.com/github/nazuna-0/WorkSheets_AshwiniTamang/blob/WorkSheet---3/WorkSheet_3_AshwiniTamang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()
titanic = pd.read_csv("Titanic-Dataset.csv")

Saving Titanic-Dataset.csv to Titanic-Dataset.csv

**DataFrame**

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

**Problem 1 : Sorting**

In [ ]:
#1
import pandas as pd

fare = titanic[['Fare']]

fare.head()

#2
class_age = titanic[['Pclass', 'Age']]

class_age.head()

#3
survived_gender = titanic.loc[:, ['Survived', 'Sex']]

survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

**Problem 2 : Subsetting**

2.1 Subsetting Rows:

In [ ]:

#1 Fare

fare_gt_100 = titanic[titanic['Fare'] > 100 ]
fare_gt_100

#2 Pclass

first_class = titanic[titanic['Pclass'] == 1]
first_class

#3 Age

female_under_18 = titanic[(titanic['Age'] < 18) & (titanic['Sex'] == 'female')]
female_under_18

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.00,5,2,CA 2144,46.9000,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
111,112,0,3,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C
114,115,0,3,"Attalah, Miss. Malake",female,17.00,0,0,2627,14.4583,NaN,C
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,W./C. 6608,34.3750,NaN,S
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.00,0,0,35851,7.7333,NaN,Q
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.00,0,1,347054,10.4625,G6,S
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.00,0,0,367231,7.7500,NaN,Q
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,NaN,S
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,NaN,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
329,330,1,1,"Hippach, Miss. Jean Gertrude",female,16.00,0,1,111361,57.9792,B18,C
374,375,0,3,"Palsson, Miss. Stina Viola",female,3.00,3,1,349909,21.0750,NaN,S
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
389,390,1,2,"Lehmann, Miss. Bertha",female,17.00,0,0,SC 1748,12.0000,NaN,C
419,420,0,3,"Van Impe, Miss. Catharina",female,10.00,0,2,345773,24.1500,NaN,S
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
446,447,1,2,"Mellinger, Miss. Madeleine Violet",female,13.00,0,1,250644,19.5000,NaN,S
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S
504,505,1,1,"Maioni, Miss. Roberta",female,16.00,0,0,110152,86.5000,B79,S
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,NaN,S
541,542,0,3,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,347082,31.2750,NaN,S
542,543,0,3,"Andersson, Miss. Sigrid Elisabeth",female,11.00,4,2,347082,31.2750,NaN,S
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S
634,635,0,3,"Skoog, Miss. Mabel",female,9.00,3,2,347088,27.9000,NaN,S
642,643,0,3,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,27.9000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,NaN,C
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,NaN,S
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,NaN,S
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,NaN,S
780,781,1,3,"Ayoub, Miss. Banoura",female,13.00,0,0,2687,7.2292,NaN,C
781,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.00,1,0,17474,57.0000,B20,S
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,31.2750,NaN,S
830,831,1,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C
852,853,0,3,"Boulos, Miss. Nourelain",female,9.00,1,1,2678,15.2458,NaN,C
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C

2.2 Subsetting Rows by Categorical variables:

In [ ]:
#1
#.isin()
embarked_c_or_s = titanic[titanic['Embarked'].isin(['C', 'S'])]
embarked_c_or_s

#2
first_second_class = titanic[titanic['Pclass'].isin([1, 2])]
first_second_class

**Exploratory Data Analysis Practice Exercise (Q & A)**

a. Which passenger had the highest fare paid relative to their age?

In [ ]:
#1
titanic['Age'] = titanic['Age'].fillna(titanic['Age'].median())

titanic['fare_per_year'] = titanic['Fare'] / titanic['Age']

#2
high_fare_age = titanic[titanic['fare_per_year'] > 5]

#3
high_fare_age_srt = high_fare_age.sort_values(by='fare_per_year', ascending=False)

#4
result = high_fare_age_srt[['Name', 'fare_per_year']]

#5
result.head()


#???
result.iloc[0]

Name             Allison, Master. Hudson Trevor
fare_per_year                        164.728261
Name: 305, dtype: object

**3.3 Exploratory Data Analysis with Group-by Method Practice Exercise:**

Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their
class?

In [ ]:
titanic['fare_per_class'] = titanic['Fare'] / titanic['Pclass']

adult_males = titanic[(titanic['Sex'] == 'male') & (titanic['Age'] >= 18)]
adult_males_srt = adult_males.sort_values(by='fare_per_class', ascending=False)

result = adult_males_srt[['Name', 'Age', 'fare_per_class']]
result.head()

                                   Name   Age  fare_per_class
737              Lesurer, Mr. Gustave J  35.0        512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0        512.3292
27       Fortune, Mr. Charles Alexander  19.0        263.0000
438                   Fortune, Mr. Mark  64.0        263.0000
118            Baxter, Mr. Quigg Edmond  24.0        247.5208

What percent of the total number of passengers on the Titanic belonged to each age group
(e.g., child, adult, senior)?

In [ ]:
def age_group(age):
    if age < 18:
        return 'child'
    elif age < 65:
        return 'adult'
    else:
        return 'senior'

titanic['age_group'] = titanic['Age'].apply(age_group)

total_passengers = len(titanic)

group_counts = titanic['age_group'].value_counts()

group_percent = (group_counts / total_passengers) * 100

print("Percentage of passengers by age group:")
print(group_percent)

Percentage of passengers by age group:
age_group
adult     86.083053
child     12.682379
senior     1.234568
Name: count, dtype: float64