<a href="https://colab.research.google.com/github/nazuna-0/WorkSheets_AshwiniTamang/blob/WorkSheet---4/Workshop4_AshwiniTamang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
import pandas as pd
import numpy as np


uploaded = files.upload()
diab = pd.read_csv("diabetes_.csv")

Saving diabetes_.csv to diabetes_.csv

In [ ]:
#
diab.head()

#
diab.info()

#
diab.isnull().sum()

#
diab.describe()

#

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

for c in cols:
    # change all the 0 values and replace with cols mean.
    diab[c] = diab[c].replace(0, diab[c].mean())

diab.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
X = diab.drop(columns=['Outcome']).values
y = diab['Outcome'].values

print(X.shape)
print(y.shape)

(768, 8)
(768,)

In [7]:
def train_test_split_scratch(X, y, test_size=0.3, seed=42):
    # fixes randomness
    np.random.seed(seed)
    # row of data set
    idx = np.arange(len(X))\
    # randomize the pattern to avoid sequential data selection
    np.random.shuffle(idx)

    split = int(len(X) * test_size)
    test_idx = idx[:split]
    train_idx = idx[split:]                # Train indices

    X_train = X[train_idx]
    X_test = X[test_idx]
    y_train = y[train_idx]
    y_test = y[test_idx]

    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split_scratch(X, y)

In [ ]:
def euclidean_distance(p1, p2):
    if p1.shape != p2.shape:
        raise ValueError("Dimensions must match")
    return np.sqrt(np.sum((p1 - p2) ** 2))

In [ ]:
def knn_predict_single(query, X_train, y_train, k=3):
    distances = [euclidean_distance(query, x) for x in X_train]
    nearest = np.argsort(distances)[:k]
    labels = y_train[nearest]
    return np.bincount(labels).argmax()

In [ ]:
def knn_predict(X_test, X_train, y_train, k=3):
    return np.array([knn_predict_single(x, X_train, y_train, k) for x in X_test])

In [ ]:
def compute_accuracy(y_true, y_pred):
    return (np.sum(y_true == y_pred) / len(y_true)) * 100

In [ ]:
pred = knn_predict(X_test, X_train, y_train, k=3)
acc = compute_accuracy(y_test, pred)

print(f"Accuracy (Original Data): {acc:.2f}%")

Accuracy (Original Data): 70.43%